export const INITIAL_FORM = {
  tripType: 'oneway',
  departure: { label: '', city: '', postcode: '', context: '' },
  arrival: { label: '', city: '', postcode: '', context: '' },
  date: '',
  time: '',
  returnDate: '',
  returnTime: '',
  passengers: '1',
  luggage: '1',
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  flightNumber: '',
  notes: '',
};
